sources:
- name: test_daquv
  database: default_db
  schema: default_schema
  tables:
  - name: account_detail
  - name: bank_transaction
  - name: branch_info
  - name: customer_info
  - name: shop_transaction
- name: seedbab_daquv
  database: default_db
  schema: default_schema
  tables:
  - name: tr_frcs_clsf_c
- name: default
  database: default_db
  schema: default_schema
  tables: []
